# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an Nginx image to serve static files
FROM nginx:alpine

# Copy the static files to the Nginx HTML directory
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
